inputQueries:
  - SELECT * FROM ig.result
  - SELECT * FROM views.views

viewports:
  - view: view_1
    layer: 1
    left: 0.5
    right: 0.5
    top: 0.5
    bottom: 0.5

modelMappings:
  - disTypes: ["4:198:2:1:0:0:7"]
    model: c17
  - disTypes: ["1:225:2:8:0:1:1", "2:225:2:8:0:0:1"]
    model: chaff
  - disTypes: ["1:225:2:1:1:1:9"]
    model: f18
  - disTypes: ["1:225:1:2:0:3:1"]
    model: aim9
